kernel-headers: msm-4.19: Fix sched_param redef
In file included from bionic/libc/include/pthread.h:41:
bionic/libc/include/sched.h:99:8: error: redefinition of 'sched_param'
   99 | struct sched_param {
      |        ^
This renames kernel's sched_param to __kernel_sched_param to avoid conflict.

Signed-off-by: Masood <163732055+Masood-J@users.noreply.github.com>
Signed-off-by: Aeoniixx <aeoniixx@gmail.com>